### ISSUE TITLE
task, assignment and unit

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#234]
What's the relation of task, assignment, and unit?

**Comment by JackUrb** [comment]
Hi @WilliamsToTo: The docs for our data model are still forthcoming, but in short:

- `Task`: We use this to group some collection that needs to be done, but won't necessarily be collected all in one go. You may have collections that are just one instance, or you may have ones that you need to launch a few times (to cover all cases, add new things to collect after initial rounds, etc) and the `Task` class lets us group all of these under one `task_name`.
- `TaskRun`: This class represents a single collection instance, where a set of initial parameters of what to launch, how, etc. are stored. Mephisto uses the information in a `TaskRun` during the run to coordinate assigning workers to assignments, and so on. Every time you initialize an `Operator` and call one of the methods to launch a task, you create a `TaskRun`.
- `Assignment`: This can be thought of as a whole task that needs to be accomplished, like "Collect a conversation" or "Annotate this specific image". A key detail here is that, even if an `Assignment` has multiple parts, these are structured such that no worker can complete more than one of the parts of that `Assignment`. This is useful for doing things like setting up tasks with multiple workers, getting inter-annotator agreement on an annotation, etc. A `TaskRun` is comprised of `Assignment`s.
- `Unit`: This class represents a single sub-component of an `Assignment`, or the unit of work that will be exposed to an individual worker.

And two others you haven't asked about but likely will run into while using Mephisto:
- `Worker`: This represents a worker across all tasks tracking all work that they've done for you under Mephisto. They have a local `worker_id` that is unique to the Mephisto db, but is separate from the id's that come from the `CrowdProvider`, like MTurk. If you want to get the local worker_id based on an MTurk id though, you can use `MTurkWorker.get_from_mturk_worker_id(...)`
- `Agent`: This class represents a `Worker` associated with a `Unit`, in that you can check the status of an `Agent` to see if they've completed a task, returned it, etc. It is distinct from a `Unit` because when a worker leaves a task, it is possible for another worker to attempt it. Thus `Agent` to `Unit` is a many-to-one relationship.

**Comment by WilliamsToTo** [comment]
Thank you very much.
