### ISSUE TITLE
property for agent.observe()

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/Mephisto#241]
What properties we can use in the dict of agent.observe(). From `examples/parlai_chat_task_demo/demo_worlds.py`, we know there are `id, text, task_data, respond_with_form, type, question, choices`. Besides those properties, is there any other properties?

Which files should I modify if I want to add a new property?

**Comment by JackUrb** [comment]
These properties are modeled after what ParlAI uses in their tasks. Generally, they should match the contents of the [`Message`](https://parl.ai/docs/core/messages.html) class. We additionally use the `task_data` field to store any additional information about the task, such as `respond_with_form` and the various form options, however at the moment `respond_with_form` is the only built-in functionality of this type. 

In designing your own tasks, if you need to change something and have it be accessible in the frontend, the `task_data` field is where you should be putting your new fields, and you can directly do this in your world. You can then access this `task_data` both in-task in `taskContext` in the javascript (pulling it out from `appContext` as done [here](https://github.com/facebookresearch/Mephisto/blob/cd1e4a4e72a30360e4df6e300944d25638b0d7b4/packages/bootstrap-chat/src/composed/BaseFrontend.jsx#L89)), or later on when reviewing the data.

**Comment by WilliamsToTo** [comment]
I'm new to frontend programming.  
I use `parlai_chat_task_demo` task and run it through `python parlai_test_script.py --use-custom-task true`. 
I'm trying to make a little change on the frontend, so I change the _width_ of a button at `parlai_chat_task_demo/webapp/node_modules/bootstrap-chat/src/FormResponse.jsx`. Then I run "npm install; npm run dev" under `webapp/` directory.
But, after I clear the cache on the browser and open the webpage, the size of button does not change.

Is there anything wrong of my steps?

**Comment by WilliamsToTo** [comment]
Thanks. Actually what I want to do is to use searchable dropdown menu instead of the original one. I have found a suitable component, I'm trying to figure out how to integrate it into mephisto.
Does mephisto support such kind of modification on the frontend?

**Comment by JackUrb** [comment]
Considering you have complete control of your `main.js` and what you pull from the `bootstrap-chat` package, it's _possible_ to do any specific replacement that you want, however without a decent understanding of React it can be somewhat daunting. This is why we provide the `renderMessage` and `renderSidePane` methods for `ChatApp`. 

You could create your own `ChatApp` modeled after this one in order to make direct modifications to portions of the `ResponsePane`, however I think the goal of #238 is to provide a method like `renderMessage` or `renderSidePane` for the response component. This would let you _just_ make an altered version of that component, and pass it in.

**Comment by pringshia** [comment]
Closing this for now. @WilliamsToTo - feel free to reopen or repost if you have further questions.
