### ISSUE TITLE
How to dynamically publish HITs when previous HITs have been returned or submitted?

### ISSUE THREAD

**Issue by easonnie** [facebookresearch/Mephisto#278]
Hi,

I have been trying the `Static React Task`. I found that the number of published HITs is decided by the number of items in the `shared_state.static_task_data`. I was wondering whether there is a way to dynamically publish HITs rather than post all of them at the beginning. I'm asking because if we post all the HITs (say 1000) at the beginning, there might be too many concurrent working assignments, and the backend might not be able to handle.

Ideally, it would be better if we can also dynamically publish HITs base on the previously collected HITs.

Sorry to bother if it's already posted somewhere or in some examples.

**Comment by JackUrb** [comment]
Hi @easonnie - Good question! This feature is coming officially very soon (shortly after #224). The code is already present though, and we already have some users testing the functionality. To manually enable it earlier you can change the default value [here](https://github.com/facebookresearch/Mephisto/blob/0b30b7b3feb2a8e7f57f1841a4698604a08a54d2/mephisto/core/task_launcher.py#L57).

**Comment by easonnie** [comment]
Hi @JackUrb - Thank you for the quick reply and the pointer! I just skimmed through the code and I'm not sure whether my understanding is correct. So, basically, the `task_data` will be stored in a queue (presumably thread-safe), `units` will be launched dynamically by getting data from the queue, and unsuccessful HITs will be "requeued". 

Just want to check my mental model is correct. 🙂

**Comment by JackUrb** [comment]
If you're using the Static React flow, Units that are returned or otherwise incomplete already will be made available for another person to take them. If you set the `max_num_concurrent_units`, then the only additional change is that only that number of Units will be launched at once. Then when a unit is successfully completed, Mephisto will launch the next one in the queue.

#224 is taking this one step further, allowing requeueing of live tasks. The important difference compared to the static tasks is that a live task requirers multiple people connected at the same time to complete, and if one disconnects we shouldn't be penalizing the other worker for it (and so they need to be able to submit their side). As such, live tasks are a little more complicated to ensure the correct number are completed properly.

Overall though your understanding is correct, the `TaskLauncher` maintains a queue of tasks that need to be launched, and the launcher works through ensuring only `max_num_concurrent_units` of them are active at a time.

**Comment by easonnie** [comment]
Hi @JackUrb, I would like to follow up on this thread. I was wondering what would be the better solution to pass in the `max_num_concurrent_units` argument to the Launcher. So far, the argument doesn't seem to be passed to the launcher in the static react example. 

https://github.com/facebookresearch/Mephisto/blob/e574ae1dbc610d9a194b9c4484e069d31c18a5a5/examples/static_react_task/run_task.py#L94

https://github.com/facebookresearch/Mephisto/blob/e574ae1dbc610d9a194b9c4484e069d31c18a5a5/mephisto/operations/operator.py#L270

**Comment by JackUrb** [comment]
We've added functionality to pass along `max_num_concurrent_units` in #405. This should make it easier to manage setting this value. Feel free to reopen this issue if there's more you need resolved.
