### ISSUE TITLE
Using MTurk qualifications (age, country, master, etc)

### ISSUE THREAD

**Issue by felixkreuk** [facebookresearch/Mephisto#281]
Hi, thanks for the very cool repo!

I am working on speech synthesis and am trying to use Mephisto for Mean Opinion Score (MOS) tests.
I was able to follow the examples to create a MOS task (maybe I would submit a PR later to add it to examples?).
The thing I am not able to do is set qualifications for turkers.

When I use the mturk web-ui it allows me to set qualifications, specifically:
* Country of origin
* Age
* Master turkers
* Etc

I thought that a natural place to look for such qualifications is in the conf file, but I didn't find it in the examples. Could you point me to how its done please?

Thanks!

**Comment by JackUrb** [comment]
Hi @felixkreuk, I'm glad you're getting use out of it! MTurk-specific qualifications are something we're definitely still improving the flow for adding. Part of this was added in #190, though the implementation has changed a bit since then. Eventually we'll expose some utilities that cover the manual part of creating the qualification objects and looking up their IDs.

At the moment though, these can be specified by adding a `mturk_specific_qualifications` attribute to your `shared_state` before passing it to an `Operator`. These later get added to the MTurk deployment [here](https://github.com/facebookresearch/Mephisto/blob/164cb7377965bc5ee41fd22f11f28b59fd6f6b7b/mephisto/providers/mturk/mturk_provider.py#L128). You can then apply the qualifications in the format that AMT expects, as noted in [their docs](https://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html#ApiReference_QualificationType-IDs).

For example, you could do:
```
...
shared_state.mturk_specific_qualifications = [
        {
             "QualificationTypeId": "00000000000000000040",
             "Comparator": "GreaterThanOrEqualTo",
             "IntegerValues": [1000],
             "ActionsGuarded": "DiscoverPreviewAndAccept",
        },
]
...
```
to only allow workers who have had more than 1000 accepted HITs.

**Comment by felixkreuk** [comment]
Hi @JackUrb thanks for the quick reply, helped a lot. I am now able to create HITs with qualifications as you suggested :) 

If it's ok, I have another question.
1. Can I compartmentalize experiments? e.g., have 2 different experiments for model A and for model B.
2. Once the experiment is over, is there a way for me to backup the results to some csv? 
3. Once the experiment is over, how do I "reset the db"?

Thanks again for the help

**Comment by JackUrb** [comment]
Of course - I think you'll find the `task_name` parameter is particularly helpful for some of this. We often use `task_name` to compartmentalize pilot rounds as well as different experiments, like `light-dialogue-pilot-1` before launching the full `light-dialogue` task for instance in order to be able to separate the data out.

1. If you set `mephisto.task.task_name` differently for each model, then later when you query data you can refer to them via this task name. 
2. At the moment we don't have a quick script for dumping data from a run, but the [`examine_results.py`](https://github.com/facebookresearch/Mephisto/blob/f24987cc9c8dcbf9761e650221977bb914215265/examples/simple_static_task/examine_results.py#L17) example shows how you can get all work for a specific task (by task name) and then later get the [data from each unit](https://github.com/facebookresearch/Mephisto/blob/f24987cc9c8dcbf9761e650221977bb914215265/examples/simple_static_task/examine_results.py#L63).
3. There's no need to reset the db, you can just choose a different task name for what you work on beyond this point. If you want a way to archive old runs and expunge their data, we're still working on a flow for this as well.

**Comment by felixkreuk** [comment]
Thanks!

**Comment by felixkreuk** [comment]
Hi @JackUrb sorry for bothering, I have another small question.
When I run the static task example (with onboarding) locally, I am able to see the onboarding test.
However, when I run in MTurk sandbox, there is no onboarding test. Am I doing something wrong?
Thanks

**Comment by felixkreuk** [comment]
@JackUrb, I created a basic audio Mean Opinion Score (MOS) task example. Would you like me to create a PR and add it to existing example? I'm think others can further improve on that as well.

**Comment by felixkreuk** [comment]
@JackUrb 
also, is there a way to limit the number of HITs a single worker can take? e.g., I have 100 HITs but would like for each worker to be able to only work on 5.

**Comment by JackUrb** [comment]
Happy to review a PR for that, I think that MOS is probably a fairly common use case and the reference would be helpful.

Re: HIT limits, you can use [`mephisto.task.maximum_units_per_worker=?`](https://github.com/facebookresearch/Mephisto/blob/f24987cc9c8dcbf9761e650221977bb914215265/mephisto/data_model/task_config.py#L74) and this limit will be shared across all task runs with the same `task_name`.
