### ISSUE TITLE
Improve integration with hydra 

### ISSUE THREAD

**Issue by ytsheng** [facebookresearch/Mephisto#399]
Repro step: `python run_mturk.py` in https://github.com/facebookresearch/dynabench/blob/master/annotators/run_mturk.py with the below change.

ideal setting:
<img width="433" alt="Screen Shot 2021-02-19 at 10 19 04 AM" src="https://user-images.githubusercontent.com/1545487/108559851-f9212e80-729f-11eb-8525-ccb89e0d9948.png">

revised/less ideal setting:

<img width="445" alt="Screen Shot 2021-02-19 at 10 49 34 AM" src="https://user-images.githubusercontent.com/1545487/108559996-2b329080-72a0-11eb-883f-04091eb41fc4.png">
<img width="296" alt="Screen Shot 2021-02-19 at 10 49 49 AM" src="https://user-images.githubusercontent.com/1545487/108560037-3b4a7000-72a0-11eb-93a5-4aad8dd2d373.png">

We should not be using json.dumps in `build_router.py`; Hydra recommends using pickle.

**Comment by JackUrb** [comment]
> We should not be using json.dumps in `build_router.py`; Hydra recommends using pickle.

Are you referring to this line:
https://github.com/facebookresearch/Mephisto/blob/1df548c0827864ef83ac6a1ffb77d2886d7ac93d/mephisto/abstractions/architects/router/build_router.py#L83

We have to have the dump there be `json` compatible as anything in that is being directly packaged up and delivered to the frontend `taskConfig` variable, accessible from the `useMephistoTask` hook. You can trace what's being added by the `get_frontend_args` to see this isn't the source of the issue.

Though I do know where the usage of `json` comes from though: 
https://github.com/facebookresearch/Mephisto/blob/5852aecc7647d4f1655c09de3698396dea0e49dd/mephisto/operations/operator.py#L188
Which we use so that we can later load the same setup from the db:
https://github.com/facebookresearch/Mephisto/blob/1df548c0827864ef83ac6a1ffb77d2886d7ac93d/mephisto/data_model/task_run.py#L53

The key design goal here though is that we want to be able to _store_ the exact arguments that were used _in the database_, for which a pickle isn't quite appropriate. Is there an alternate for being able to create the static yaml representation?


Also it would be useful to see the context on "hydra recommends pickle", there may be more there that's useful.

**Comment by omry** [comment]
Context on pickle recommendation:

It depends on what you are trying to achieve.
OmegaConf support yaml in general, you can use OmegaConf.to_yaml(cfg, resolve=True) to convert to a resolved yaml representation.

The downside is that you lose type safety when you load the yaml (Structured Configs), which may or may not be an issue.
If you want the highest fidelity in reconstruction, you should use pickle. Of course - this expose you to changes from code changes (new fields in your dataclasses may show up suddenly).
Like many things in life, it's a trade-off.

I think storing the pickle string in the database can work well, if you don't mind losing type safety, you can store and restore the yaml string:
```
yml = OmegaConf.to_yaml(cfg, resolve=True)
cfg2 = OmegaConf.create(yml)
```

A word about resolving (we both used resolve=True in our examples):
This is another tradeoff:
If you are consuming the config with OmegaConf (seems like you are), and you may be mutating the config later (for example in code) you should probably not resolve.

```python
In [1]: from omegaconf import *

In [2]: cfg = OmegaConf.create({"a": 10, "b": "${a}"})

In [3]: cfg.a
Out[3]: 10

In [4]: cfg.b
Out[4]: 10

In [5]: cfg.a = 20

In [6]: cfg.b
Out[6]: 20

In [7]: cfg2 = OmegaConf.create(OmegaConf.to_yaml(cfg, resolve=True))

In [8]: cfg2
Out[8]: {'a': 20, 'b': 20}

In [9]: cfg
Out[9]: {'a': 20, 'b': **'${a}'}**
```

Changing a in cfg2 will not have the same meaning as changing it in cfg.
