### ISSUE TITLE
Save data when timeout occurs

### ISSUE THREAD

**Issue by federicoruggeri** [facebookresearch/Mephisto#436]
Dear All,
I was wondering if there's a simple way to retrieve data even when a timeout occurs.
For instance, if we consider the `parlai_chat_task_demo`, the last part of the `run_assignment` function in `parlai_chat_task_runner.py` [lines 238-253] is skipped when a timeout occurs. Thus, workers' chat is never saved into the database. Am I correct on this part?

I'm not sure if this flexibility is needed when a real test scenario is considered. However, it might be quite useful during development in order to avoid losing some interesting data. (still marking the retrieved data with a timeout flag to distinguish it from well-formed and valid data).

Thanks in advance!

**Comment by JackUrb** [comment]
Hi @federicoruggeri - At the moment all of the details of the chat should still be saved, however we do not call `prep_save_data` as we never requested that users make that function tolerant of being called in an incomplete world state. The previous turns are still recorded in the `Agent`'s state, and should be retrievable using a script inline with the [examine_results.py](https://github.com/facebookresearch/Mephisto/blob/master/examples/simple_static_task/examine_results.py) example, though the given assignments will be in a mixed state due to one of the agents disconnecting.

**Comment by federicoruggeri** [comment]
Hi @JackUrb,
Once again, thanks for your quick reply!
You are right, I've completely forgotten to check each Worker data fields in `examine_results.py`. 
I was more focused on the runtime execution flow while I could just have inspected saved data more deeply.
