### ISSUE TITLE
How to implement wizard of woz collection?

### ISSUE THREAD

**Issue by liangrz15** [facebookresearch/Mephisto#469]
Hi,

I am working on a dialogue task collection, where the role is either an expert or a normal worker. The examples only show the situation that each worker is given the exactly same role as well as task description. My question is how I can implement wizard of woz collection.

To be more specific, below are my needs:

1. In each of the dialouge, one worker should be assigned the role of **expert**, and another worker should be assigned the role of **normal worker**.
2. The onboarding information for **expert** and **normal woker** should be different.
3. The SidePane UI for the **expert** and **normal worker** should be different.
4. Different **normal workers** are facing different tasks, so the details of task description of them are different.

I'll be very grateful if you can help me with this. :)

**Comment by JackUrb** [comment]
Hi @liangrz15 - before you jump into this, approach, we've found it's easier to maintain a system where your workers are onboarded for _both_ roles, and then assigned the correct role as they come in. This helps ensure that you always have workers pairing, rather than having a bunch of people accepting the normal role and nobody accepting the expert. In order to deal with task difficulty differences, you can bonus the expert worker if you're finding workers feel the pay is unfair for more complicated work. 

From this perspective, we definitely cover the idea of assigning roles and displaying different UIs for different roles. All you need to do is have your `ParlAI` world set the `id` of the agents in its `__init__` method, and then your `renderSidePane` method can return a different component depending on if `expert` or `worker` is in the `taskContext.currentAgentNames` field.

**Comment by liangrz15** [comment]
Hi @JackUrb , thank you for your quich reply! It indeed solved part of my problem. However, I found some issues of this method, and I wonder how these issues can be overcome:

1. It seems that the **taskContext.currentAgentNames** array does **not** appear until both workers get connected. How can the first worker get the correct information while waiting for the second worker?
2. Besides the agent name, I want to add some extra information (e.g., show different articles to different **normal workers** in side pane). How can I achieve this in `ParlAI` world? 

I'll be very grateful if you can help me with this. :)

**Comment by JackUrb** [comment]
Hi @liangrz15, sorry for the delay here:

1. Correct, it isn't until the world starts that we're able to determine who is who. When workers haven't been paired yet, that means that the `Supervisor._launch_and_run_assignment` call isn't made yet. In theory a hook could be added to `Supervisor._assign_unit_to_agent` to allow blueprints to register pre-task callbacks (run after assigning, but before `run_assignment`), but I'm not sure the use case is strong enough for the added complexity. If it means anything, you can likely use the time spent waiting as a sign of being the _first_ worker in the set that you assign later, but I haven't tested that yet. (Ie - if the worker waits more than X seconds, they're _most likely_ being assigned the first role).
2. For this, you can just call `agent.observe()` on the individual agent you want to send information to. If you pass `agent.observe({'text':'', 'task_data': {'something': 'value'}}), then `{"something": "value"}` becomes available in the `taskContext` object in the frontend. More information on this is available in the [`bootstrap-chat` guides](https://github.com/facebookresearch/Mephisto/tree/master/packages/bootstrap-chat#the-appcontext-argument).

**Comment by pringshia** [comment]
Closing for now, please feel free to reopen the issue if there are any further questions.
