### ISSUE TITLE
mturk pairing

### ISSUE THREAD

**Issue by ninadu07** [facebookresearch/Mephisto#623]
Is there a way in Mephisto to limit the number of times (turker1, turker2) can be paired with each other for a dialogue task?

**Comment by JackUrb** [comment]
Interesting question. It's certainly possible, though somewhat involved. I'd also note that this comes with the risk of increasing the time that it takes for workers to pair, which may frustrate workers if not monitored closely. In any case the goal would be to ensure that [`get_valid_units_for_worker`](https://github.com/facebookresearch/Mephisto/blob/ae96ae558cffc7e76daa73cf77537ee2aa83ae8b/mephisto/data_model/task_run.py#L95) wouldn't consider a unit on an assignment paired with a partner you've already had some number of times before as a valid unit. We allow for an arbitrary filtering function to be supplied in [`worker_can_do_unit`](https://github.com/facebookresearch/Mephisto/blob/4937db1184a2a8d9b30f0d20bef0bc0f098a5238/mephisto/abstractions/blueprint.py#L68-L70) which ends up used [`here`](https://github.com/facebookresearch/Mephisto/blob/ae96ae558cffc7e76daa73cf77537ee2aa83ae8b/mephisto/data_model/task_run.py#L160). 

A valid implementation could then be:
```python
# in run_task.py's main
pairings_list = defaultdict(lambda: 0)
MAX_PAIRS = 5
def only_allow_max_pairs(worker, unit):
  assignment = unit.get_assignment()
  other_units = assignment.get_units()
  assigned_agents = [u.get_assigned_agent() for u in other_units]
  existing_agents = [a for a in agents if a is not None]
  if len(existing_agents) == 0:
    # nobody else is assigned to this yet
    return True
  else:
    # assuming two person chats
    if pairings_list[set([worker.db_id, existing_agents[0].get_worker().db_id])] < MAX_PAIRS:
      return True

shared_state = SharedParlAITaskState(
  worker_can_do_unit=only_allow_max_pairs,
  world_opt={'pairings': pairings_list},
  ...
)
...

# in world module's 
def make_world(opt, agents, ...):
  pairings_list = opt['pairings']
  worker_ids = [a.mephisto_agent.get_worker().db_id for a in agents]
  pairings_list[set(worker_ids)] += 1
```

I haven't tested it explicitly, but I believe it should work. Let me know if you have any questions!

Note, I'd strongly suggest using the [`SingletonMephistoDB`](https://github.com/facebookresearch/Mephisto/pull/432) with `mephisto.database._database_type=singleton` if you're doing this type of pairing, as the addition get calls may slow the system down otherwise.

**Comment by JackUrb** [comment]
Closing as there hasn't been a followup since the suggestion. I hope this worked out! Feel free to reopen with more context if needed.
