### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by fsysean** [facebookresearch/Mephisto#680]
After installation, I found this error. I googled and found that "the fcntl module is not available on Windows. The functionality it exposes does not exist on that platform."

Does this mean this project is not working on Windows?

**Comment by JackUrb** [comment]
At the moment Mephisto has only been tested on unix and linux systems. I'm not sure which package specifically is asking for `fcntl` (appears to be one of our dependents), but I imagine it's due to our dependence on the `sqlite` python package. One could implement a windows-friendly version of the `MephistoDB` interface to get things working on windows.
