### ISSUE TITLE
Handling Mephisto service crash

### ISSUE THREAD

**Issue by eranhirs** [facebookresearch/Mephisto#685]
Crowdsourcing tasks can often take a few days, and it is possible that the server running Mephisto will crash / reboot.
I have a few questions, assuming that:
1. I am using MTurk.
2. I am not using websockets.

What happens when the turkers submit and the service is unavailable (and my code did not run `shutdown` before crashing)? Since the information is saved on MTurk, I guess we can still download them later and this should not influence the process.
Is it possible to reconstruct the `Operator` object in such a way that it will continue from the previous state (i.e. the MTurk hits)? This way we can always restart the Mephisto service and eventually get a clean shutdown once the task is truly finished.

Thanks!

**Comment by JackUrb** [comment]
Hi @eranhirs, thanks for opening an issue! We're working on increasing stability in these types of situations. While your proposed functionality would be nice (relinking to _existing_ MTurk hits on a relaunch before proper shutdown), it would be difficult to implement in the platform-agnostic approach that Mephisto takes. As another note, once Mephisto crashes it is impossible for a worker to accept a new task, as even in a static setup (without websockets) the server determines worker eligibility and which data to assign.

I understand that not every setup will necessarily be stable, so to this end we have the following existing mitigations for improper shutdowns:
1. `MTurkAgent.attempt_to_reconcile_submitted_data()` is a utility function that can be called on an agent to try and get data that has been saved on the MTurk side but didn't make it to Mephisto. Calling `[u.get_status() for u in task_run.get_units()]` should automatically identify agents that are in this broken state, and attempt to reconcile.
2. `mephisto.scripts.mturk.cleanup.py` can be used to properly find and shutdown tasks that are still running after an incomplete shutdown, and should be used after any improper shutdown run with an MTurkProvider

These however aren't sufficient enough, and I'm looking towards the following extensions in the future:
1. `v1.1`: Easy access to extract `assignment_data` for all incomplete units in a `TaskRun` using the `DataBrowser`, such that it should be easier to add `relaunch_from=<task_run_id>` flags to any run script. 
2. `v1.1`: Detection of incomplete shutdowns, such that the `cleanup.py` script can be automatically invoked by `mephisto check`. We could then begin running `mephisto check` by default on any initialization of a Mephisto operator.
3. `v1.2`: Standard script tooling to add `relaunch_from` to the default `RunScriptConfig`.
I'm also open to scoping other ideas for contributors to work on as well. Let me know if this is helpful!

**Comment by eranhirs** [comment]
Hi @JackUrb , thank you for your elaborated response!

I see, it makes sense to me now that turkers can't start a new HIT while the service is offline. Perhaps they should see an error message in case the HIT wasn't removed? Given the future extensions you mentioned, the `relaunch_from` functionality makes the most sense to me. Otherwise, I would need to filter out the data already completed which sounds messy.


Better yet, given the aforementioned error message we add when starting a HIT, I don't see why we need to delete the HITs on shutdown.
Also, if the turker already started a task, they can even submit it, and then, as you mentioned, we can fetch the information from MTurk. This is based on what you said, "the server determines worker eligibility and which data to assign", nothing about submission.

It will make it easy to avoid problems such as:
1. 2 out of 3 turkers already answered the hit and we only need 1 more response.
2. A turker is currently online and we are deleting the HIT.

I would delete the HITs only based on explicit request.

**Comment by JackUrb** [comment]
A few more clarifications:

> Perhaps they should see an error message in case the HIT wasn't removed? 

This is possible up until the point that the architect server is taken down. Before this we can include a timeout message like "We were unable to connect to the backend server, please try again later". If you're using Heroku for instance, once the server goes down MTurk blindly directs workers to a default "this heroku app doesn't exist" page, and we have no way to detect that in the underlying HIT to display a different message to workers.

> I don't see why we need to delete the HITs on shutdown.

The deletion flow is a little complicated to track, as we still have to take down HITs after the server goes down because MTurk workers can still 'access' them but then end up being shown an error. HITs that are even actively being worked on (from a load prior to the crash/shutdown) may return their HIT and a new worker could accept it only to find it broken. Technically what we're doing is "expiring" the HITs on shutdown to prevent workers from being able to access them in a broken state. 


It's definitely the case that at the moment Mephisto runs more than is _absolutely necessary_ for the simpler cases of launching a crowdsourcing task, but this is because it focuses on the flexibility required to enable complex flows that are not otherwise possible. Certainly there's some interest in running in a "headless" mode for static tasks with no additional capabilities enabled, but I'd caution to even encourage a route like this as it is difficult to ensure quality without at the least one of onboarding, validation units, or gold units, which all require server-side involvement.

**Comment by eranhirs** [comment]
> This is possible up until the point that the architect server is taken down. 

I guess that is a fair assumption to make (if we don't remove the HITs we should also avoid removing the architect).

> MTurk workers can still 'access' them but then end up being shown an error.

Given the use case that the service sometimes reboots for a short period (restating that crowdsourcing tasks often take a few days), I don't think this should prevent us from pursuing this direction.
Although, it can also probably be solved by having multiple pods and running `shutdown` only if all pods are unavailable.

> Certainly there's some interest in running in a "headless" mode for static tasks with no additional capabilities enabled, but I'd caution to even encourage a route like this as it is difficult to ensure quality without at the least one of onboarding, validation units, or gold units, which all require server-side involvement.

OK, that makes sense.

>  It's definitely the case that at the moment Mephisto runs more than is absolutely necessary for the simpler cases of launching a crowdsourcing task, but this is because it focuses on the flexibility required to enable complex flows that are not otherwise possible.

I see, thank you for this clarification 😊  I appreciate your focused vision!
