### ISSUE TITLE
How to export the data?

### ISSUE THREAD

**Issue by xksteven** [facebookresearch/Mephisto#812]
I couldn't really find out how to do this in the docs.  How should I export the data collected to a json or CSV or some other format?

From the example with [reviewing data](https://mephisto.ai/docs/guides/tutorials/first_task/#13-reviewing-tasks). 

I added the following to be able to export the data.  Wasn't sure if there was a better way though?

```python
import json

db = None

def format_data_for_printing(data):
    global db
    ....
    with open('results.json', 'w') as f:
        json.dump({
            "worker_name": worker_name, 
            "unit": data['unit_id'],
            "duration": int(duration),
            "status": data['status'],
            "output": outputs
            }, f)

    return f"-------------------\n{metadata_string}{inputs_string}{output_string}"
```

**Comment by JackUrb** [comment]
Hi @xksteven - we're still building out standard data exports. Generally the way to do this can be seen [under the hood](https://github.com/facebookresearch/Mephisto/blob/207cfd750987613be4c84409faf9f3fce7e7069d/mephisto/tools/examine_utils.py#L138) of how the `examine_results.py` script works:
```
data_browser = DataBrowser(db=db)
tasks = db.find_tasks(task_name=task_name)
# ...
units = data_browser.get_units_for_task_name(task_name)
# ...
for u in units:
    # ...
    print(format_data_for_printing(data_browser.get_data_from_unit(unit)))
```
The powerful tools here are packed into the `DataBrowser`, and using `get_data_from_unit` you can dump the contents to whatever format you want, rather than just printing.

I could see it being feasible for us to create some kind of generic "filtered reducer" script in the future, but for now you're not far off from expected usage, just doing it in a hacky way.

**Comment by pringshia** [comment]
Updated the docs to be slightly clearer about this in #815

**Comment by JackUrb** [comment]
Closing with the doc change. Please feel to reopen if you have more questions!
