### ISSUE TITLE
Errors when installing new dependencies

### ISSUE THREAD

**Issue by Etesam913** [facebookresearch/Mephisto#818]
## Overview
Adding a new dependency into requirements.txt causes errors to occur in the github actions workflow.

For example, 
When I added the `rich` dependency to the requirements.txt file I got this output for the test:
https://github.com/facebookresearch/Mephisto/runs/7237323897?check_suite_focus=true

The issue is not exclusive to `rich` as I also got this error when trying to add the `detoxify` dependency.

**Comment by JackUrb** [comment]
For some context, we moved away from poetry due to https://github.com/python-poetry/poetry/issues/34 causing issues with `setup.py develop` and other editable installs, which we needed to be able to do local development of tasks. This has been resolved as of Poetry 1.2, and as such the solution is to upgrade to there and then remove `requirements.txt` entirely and work from `pyproject.toml` instead. Will jump into this next week. In the meantime, feel free to skip the dependencies temporarily.

This is tied to #768
